# --- General options --- #

# url is the full website URL
# baseurl is the website's URL without the hostname

# If you are building a simple GitHub user page (http://username.github.io) then use these settings:
url: "https://github.com/data-8/"
baseurl: ""

# If you are building a GitHub project page then use these settings:
#url: "http://username.github.io/projectname"
#baseurl: "/projectname"

# Of course don't forget to change the username and projectname to YOUR username and project

# Name of website
title: DataConnect

# Short description of your site
description: A collection of data science-related resources at UC Berkeley.

# Gem installations
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate

# --- Navigation bar options --- #

# List of links in the navigation bar
navbar-links:
  Home: ""
  Academics: "academics"
  People: "people"
  Projects: "project"
  Events: "events"
  Diversity:
  - Clubs: "clubs"
  - Scholarships: "scholarships"
  - Careers: "career"
  Resources:
  - Training: "training"
  - Consulting: "consulting"
  - Technology: "technology"


# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
avatar: "/img/avatar-icon.png"

#Events Entries#
events:
  Data Connect Debut:
    - month: "August"
    - date: "28"
    - start_time: "5 PM"
    - end_time: "6 PM"
    - event_link: "https://dataconnect.berkeley.edu"
    - event_description: "The debut for the data connect initiative"
  Data Forum:
    - month: "September"
    - date: "9"
    - start_time: "6 PM"
    - end_time: "7:30 PM"
    - event_link: "https://dataconnect.berkeley.edu"
    - event_description: "A great forum to learn about data science"
  Prof. DeNero`s Talk:
    - month: "January"
    - date: "17"
    - start_time: "3 PM"
    - end_time: "4:30 PM"
    - event_link: "https://dataconnect.berkeley.edu"
    - event_description: "I love my dogs"
  Kaggle ML competition:
    - month: "March"
    - date: "15"
    - start_time: "6 PM"
    - end_time: "7 PM"
    - event_link: "https://dataconnect.berkeley.edu"
    - event_description: "Can you recognize it?"

# --- Footer options --- #

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: Berkeley Data Connect
  email: "youremail@domain.com"
  facebook: yourname  # eg. daattali
  github: BIDS-projects    # eg. daattali
  twitter: yourname   # eg. daattali
  linkedin: yourlink  # eg. "pub/dean-attali/8/946/143"
  stackoverflow:  # eg. "3943160/daattali"
 
# Select which links to show in the footer
footer-links-active:
  rss: false
  facebook: true
  email: true
  twitter: true
  github: true
  linkedin: false
  stackoverflow: false

# How to display the link to the website in the footer
# Remove this if you don't want a link in the footer
url-pretty: "dataconnect.berkeley.edu"
# --- Misc --- #

# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
#disqus: ""

# Fill in your Google Analytics ID to track your website using GA
#google_analytics: ""

# --- Don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "America/Vancouver"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true

# Exclude these files from production site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - Vagrantfile

# prose.io config
prose:
  rooturl: '_posts'
  media: 'img'
  ignore:
    - 404.html
    - LICENSE
    - feed.xml
    - _config.yml
    - /_layouts
    - /_includes
    - /css
    - /img
    - /js
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Post title"
          placeholder: "Title"
          alterable: true
      - name: "subtitle"
        field:
          element: "textarea"
          label: "Subtitle"
          placeholder: "A description of your post."
          alterable: true
      - name: "date"
        field:
          element: "text"
          label: "Date"
          help: "Enter date of post."
          placeholder: "yyyy-mm-dd"
          alterable: true
      - name: "published"
        field:
          element: "checkbox"
          label: "Publish"
          help: "Check to publish post, uncheck to hide."
  
# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189
